language: java
jdk:
- oraclejdk8
script:
- ./gradlew build
deploy:
  provider: releases
  api_key:
    secure: Kl6LiJ4ZtJ5XHnKUsEjlOAEGBP9Qxry2pCmh7XNx4/LtG7kcLZClPXRlCCnneJNlZ0l8MnNGW7+C4Kl44HGWtfZi2BBtvHa1Zx5PVVIcThnFh1998xaL+yel2ye8DbR52hWaRj69K7+mwNU+Z6eoyEPDcebamgJXBCScZRFq09yUFBxm3jpEzihjY7zC2Pi3hPFp8+lGYZbmWZXP8oSsq0oDdfb0LoOT4/jTHVA4PZYo5xRMQlC8SnwhnHQqHJ3UoeX2h405hfAINCcE+iy87jib/GCRKuIAjKhBFo4CC5JxA4bg4shuTeDOCz2OlYvWWIXTf9gK5310qUan3JPO9jkGid67ykk2VjZIeHYW4yS0c3X72L208zXyWSKrhNZSbKMP56Y5mqaTLX9LWUZivy9BFdHpTvAp0OcLYCjh81z6xoLQLOGdJiDdty08dqAhesHPJ0f8qPS3ejia+ZeySTg5pTknoK1OSAgb1+eOzEI49HNv+0Voj9ifn1x1xPc5106u1KFKgK9xHMjM2TzSo4Blwur5xBmc41cfTvJOXBEDAzVHixk8dU/8tJ6nWG1Wf+hsuiswxBkqlVur5bSLaxpYF38Ok8TyU3g6S6lKz8Qf7tFav/jSu7RpoXXVlUXEgFrGO2exIHQPpNn6y9VSHfbSeFFmOySdHgLQz3Tl9Ns=
  file_blob: on
  file: TRAVIS_BUILD_DIR/build/libs/ExponentialPower*.jar
  skip_cleanup: true
  on:
    tags: on
